### ISSUE TITLE
Footer position is incorrect.

### ISSUE THREAD

**Issue by arepoGiovanna** [ewu11/HMS#1]
The footer's "position" attribute might be wrong, because it overlaps with the main contents. That shouldn't happen. The picture below shows the example of the issue.

![footerIssue](https://user-images.githubusercontent.com/70443283/178420404-2a2aba5a-c83f-4bcc-8570-a038cae64591.png)

**Comment by ewu11** [comment]
Have fix this issue by using z-index properties. When window resizing, the footer is placed under the other elements.
